version: "3.9"

networks:
  lkbackend:

services:
  auth-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest-ci
    hostname: auth-server
    ports:
      - 8881:8080
    environment:
      - LIVEKIT_URL=ws://localhost:7880
      - LIVEKIT_KEY=devkey
      - LIVEKIT_SECRET=secret
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - lkbackend

  livekit:
    image: livekit/livekit-server:latest
    command: --dev --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
      - "50100-50200:50100-50200"
    volumes:
      - ./backend/livekit.yaml:/etc/livekit.yaml
    networks:
      - lkbackend

  redis:
    image: redis:6-alpine
    command: redis-server /etc/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./backend/redis.conf:/etc/redis.conf
    networks:
      - lkbackend
